#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
  path: /authentication_token
  methods: ['POST']
api_refresh_token:
  path: /api/token/refresh
start:
  path: /


