image: php:8.0-alpine

options:
    max-time: 10

definitions:
    caches:
        composer: /tmp/cache
    steps:
        -
            step: &validate-php-syntax
                name: Validate PHP Syntax
                script:
                    - apk --no-cache add parallel
                    - find . -name \*.php | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
        -
            step: &check-coding-styles
                name: Check Coding Styles
                script:
                    - bin/php-cs-fixer fix ./backend --config=.php-cs-fixer.php -vv --dry-run
pipelines:
    default:
        - step: *validate-php-syntax
        - step: *check-coding-styles
    branches:
        develop:
            - step: *validate-php-syntax
            - step: *check-coding-styles
            - step:
                name: Deployment
                deployment: staging
                image: rubygem/capistrano:3.7.2
                script:
                    - gem install capistrano-composer
                    - cap staging deploy
