image: php:8.0-alpine

options:
    max-time: 10

pipelines:
    branches:
        develop:
            - step:
                name: Deployment
                deployment: staging
                image: rubygem/capistrano:3.7.2
                script:
                    - gem install capistrano-composer
                    - cap staging deploy
