image: php:8.0-alpine

definitions:
    caches:
        composer: backend/vendor
        npm-cache: frontend/node_modules

options:
    max-time: 10

pipelines:
    branches:
        develop:
            - parallel:
                - step:
                    name: Install frontend packages and build frontend
                    image: node:16.15.1
                    caches:
                        - npm-cache
                    script:
                        - cd frontend && npm ci && npm run build
                    artifacts:
                        - frontend/node_modules/**
                        - frontend/.nuxt/**
                - step:
                    name: Composer Setup
                    image: composer:2.3.7
                    script:
                        - cd backend && composer validate
                        - composer install -n --prefer-dist --no-ansi --no-progress
                    caches:
                        - composer
                    artifacts:
                        - backend/vendor/**
                        - backend/public/bundles/**

            - step:
                name: Deployment
                deployment: staging
                image: rubygem/capistrano:3.7.2
                script:
                    - gem install capistrano-composer
                    - gem install capistrano-scm-copy
                    - cap staging deploy
