dubture_f_fmpeg:
  ffmpeg_binary: '%env(resolve:FFMPEG_BINARY)%'
  ffprobe_binary: '%env(resolve:FFMPROBE_BINARY)%'
  binary_timeout: 300 # Use 0 for infinite
  threads_count: 4
  temporary_directory: /var/ffmpeg-tmp