name: creative-museum
type: php
docroot: backend/public
php_version: "8.1"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames:
  - backend.creative-museum
additional_fqdns: []
database:
  type: mariadb
  version: "10.3"
nfs_mount_enabled: false
mutagen_enabled: true
use_dns_when_possible: true
composer_version: "2"
web_environment: []
nodejs_version: "18"
webimage_extra_packages: [openssl, build-essential, sendmail, python]
hooks:
  post-start:
  - exec: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.con
  - exec: npm install -g node-gyp-build @mapbox/node-pre-gyp consola